[workspace]

members = [
    "rusty-workers-runtime",
    "rusty-workers-fetchd",
    "rusty-workers",
    "rusty-workers-cli",
    "rusty-workers-proxy",
    "rusty-workers-cp",
    "rusty-workers-playground-api",
    "prometheus",
]

[profile.release]
debug = false
lto = "thin"

# Set panic=abort because Tokio does not terminate the program on panics.
panic = "abort"
