apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __NAMESPACE__
  name: proxy
  labels:
    app: proxy
spec:
  replicas: __NUM_PROXIES__
  minReadySeconds: 30
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      namespace: __NAMESPACE__
      name: proxy
      labels:
        app: proxy
    spec:
      __MAYBE_PULL_SECRETS__
      containers:
      - name: proxy
        image: __IMAGE_PREFIX__rusty-workers-proxy__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
        env:
        - name: RUST_LOG
          value: rusty_workers_proxy=info,rusty_workers=info
        # Address of the fetch service to use.
        - name: RW_FETCH_SERVICE
          value: fetchd-service.__NAMESPACE__.svc.cluster.local:3000
        # Max I/O concurrency.
        # Concurrent I/O operations more than this amount will wait in a queue.
        - name: RW_MAX_IO_CONCURRENCY
          value: "10"
        # Max I/O operations per request.
        # Currently not enforced!
        - name: RW_MAX_IO_PER_REQUEST
          value: "50"
        # Max ArrayBuffer memory per worker.
        - name: RW_MAX_AB_MEMORY_MB
          value: "128"
        # Max CPU time per request.
        - name: RW_MAX_TIME_MS
          value: "5000"
        # List of runtime backends.
        - name: RUNTIMES
          # Query it 3 times when doing discovery
          value: runtime-service.__NAMESPACE__.svc.cluster.local:3000,runtime-service.__NAMESPACE__.svc.cluster.local:3000,runtime-service.__NAMESPACE__.svc.cluster.local:3000
        # Size of the route cache.
        - name: RW_ROUTE_CACHE_SIZE
          value: "1000"
        # Size of the app cache.
        - name: RW_APP_CACHE_SIZE
          value: "50"
        # Database URL.
        - name: RW_DB_URL
          value: "__DB_URL__"
        ports:
        - containerPort: 8080
