
global:
  scrape_interval: 2s 
  evaluation_interval: 2s 
  
scrape_configs:
  - job_name: 'rusty_workers'
    static_configs:
    - targets: ['localhost:9898']
  - job_name: 'node'
    static_configs:
    - targets: ['localhost:9100']
  - job_name: 'tikv'
    static_configs:
    - targets: ['localhost:9090']
  

